# Utilisation d'une image de base légère Python
FROM python:3.8-alpine

# Définir des variables d'environnement
ENV PYTHONUNBUFFERED=1

# Définir le répertoire de travail
WORKDIR /projet-web-tsp/django-site/todolist

# Installer les dépendances système requises
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev

# Copier les fichiers du projet Django dans le conteneur
COPY ./django-site/todolist /projet-web-tsp/django-site/todolist

# Installer les dépendances Python
RUN pip install --upgrade pip && \
    pip install -r ./requirements.txt

# Exposer le port sur lequel Django fonctionne
EXPOSE 8000

# Commande pour démarrer le serveur Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
