# Generated by Django 5.1.1 on 2024-09-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
